plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

remote_theme: pmarsceill/just-the-docs
search_enabled: true

search:
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  
color_scheme: dark
